version: 1.0.{build}
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"  
branches:
  only:
  - master  
configuration: Release
platform: Any CPU  
artifacts:
build:
  project: Owin.Security.Providers.PingFederate.sln
after_test:
  - ps: .\.nuget\pack.ps1
deploy:
- provider: NuGet
  api_key:
    secure: URwllFXj7DocZxjh46r88t4NJb1ApHqjhWHWNTF3+Z0LxJ53COkdFIuEdUT3NQTA
  artifact: /.*\.nupkg/
  